/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.distributorEnterprise;

import business.Business;
import business.enterprise.CDCEnterprise;
import business.enterprise.Enterprise;
import static business.enterprise.Enterprise.EnterpriseType.CDCEnterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.cdcenterprise.ManageVaccineCatalogJPanel;

/**
 *
 * @author Harshil
 */
public class DistributorEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DistributorEnterpriseJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Network network;
    private Enterprise enterprise;
    private Business business;
    private Organization organization;
    
    public DistributorEnterpriseJPanel(JPanel userProcessContainer,UserAccount userAccount,Network network,Enterprise enterprise,Organization organization,Business business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.network = network;
        this.enterprise = enterprise;
        this.organization = organization;
        this.business = business;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageApprovedVaccineStockCatalog = new javax.swing.JButton();
        btnManageDistributorWorkRequests = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Distributor Work Area");

        btnManageApprovedVaccineStockCatalog.setBackground(new java.awt.Color(102, 102, 255));
        btnManageApprovedVaccineStockCatalog.setText("Manage Vaccine Stock Catalog");
        btnManageApprovedVaccineStockCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageApprovedVaccineStockCatalogActionPerformed(evt);
            }
        });

        btnManageDistributorWorkRequests.setBackground(new java.awt.Color(102, 102, 255));
        btnManageDistributorWorkRequests.setText("Manage Distributor Work Requests");
        btnManageDistributorWorkRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDistributorWorkRequestsActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/distributorEnterprise/logo_vaccine_lg.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageApprovedVaccineStockCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageDistributorWorkRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(btnManageApprovedVaccineStockCatalog)
                .addGap(45, 45, 45)
                .addComponent(btnManageDistributorWorkRequests)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageApprovedVaccineStockCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageApprovedVaccineStockCatalogActionPerformed
        // TODO add your handling code here:
        
        ManageApprovedVaccineStockCatalogJPanel mavscjp = new ManageApprovedVaccineStockCatalogJPanel(userProcessContainer,userAccount,network,enterprise,organization,business);
        userProcessContainer.add("ManageApprovedVaccineStockCatalogJPanel",mavscjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
               
    }//GEN-LAST:event_btnManageApprovedVaccineStockCatalogActionPerformed

    private void btnManageDistributorWorkRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDistributorWorkRequestsActionPerformed
        // TODO add your handling code here:
        
        DistributorWorkRequestsJPanel djp = new DistributorWorkRequestsJPanel(userProcessContainer,userAccount,network,enterprise,organization,business);
        userProcessContainer.add("DistributorWorkRequestsJPanel",djp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageDistributorWorkRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageApprovedVaccineStockCatalog;
    private javax.swing.JButton btnManageDistributorWorkRequests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
