/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.medicalEnterprise.sites.VaccineStockCatalog;

import business.Business;
import business.enterprise.Enterprise;
import business.enterprise.MedicalEnterprise;
import business.network.Network;
import business.organization.useraccount.UserAccount;
import business.site.Site;
import business.site.siteVaccineOrder.VaccineMasterOrderCatalog;
import business.site.siteVaccineOrder.VaccineOrder;
import business.site.siteVaccineOrder.VaccineOrderItem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harshil
 */
public class VaccineOrderHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VaccineOrderHistoryJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Network network;
    private MedicalEnterprise medicalEnterprise;
    private Site site;
    private Business business;
    private VaccineMasterOrderCatalog vaccineMasterOrderCatalog;
    private Enterprise enterprise;
    
    public VaccineOrderHistoryJPanel(JPanel userProcessContainer,UserAccount userAccount,Network network,Enterprise enterprise,Site site,Business business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.network = network;
        this.enterprise = enterprise;
        this.medicalEnterprise = (MedicalEnterprise)enterprise;
        this.site = site;
        this.business = business;
        
        System.out.println(enterprise.getVaccineMasterOrderCatalog());
        
        this.vaccineMasterOrderCatalog = enterprise.getVaccineMasterOrderCatalog();
        lblUserAccount.setText(userAccount.getUsername());
        populateOrderHistoryTable();
        
        
        
        
        
    }

    
    private void populateOrderHistoryTable()
    {
        int rowCount = tableOrderHistory.getRowCount();
        DefaultTableModel dtm =(DefaultTableModel)tableOrderHistory.getModel();
        dtm.setRowCount(0);
        
        for(VaccineOrder vaccineOrder: vaccineMasterOrderCatalog.getVaccineOrderList())
        {
            System.out.println(vaccineOrder.getVaccineOrderID()+" "+vaccineOrder.getUserAccount());
            if(vaccineOrder.getUserAccount()==userAccount)
            {
                Object row[] = new Object[3];
                row[0] = vaccineOrder.getVaccineOrderDate();
                row[1] = vaccineOrder;
                row[2] = vaccineOrder.getVaccineOrderStatus();
                dtm.addRow(row);
            }
        }
    }
    
    
    
    
    
    public void populateOrderItemTable()
    {
        int rowCount = tableOrderItem.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)tableOrderItem.getModel();
        for(int i =rowCount-1;i>=0;i--)
        {
            dtm.removeRow(i);
        }
        
        int selectedRow = tableOrderHistory.getSelectedRow();
        if(selectedRow>=0)
        {
            VaccineOrder order = (VaccineOrder)tableOrderHistory.getValueAt(selectedRow,1);
            
            for(VaccineOrderItem orderItem: order.getVaccineOrderItemList())
            {
                Object row[] = new Object[4];
                row[0] = orderItem;
                row[1] = orderItem.getVaccinePrice();
                row[2] = orderItem.getQuantity();
                row[3] = orderItem.getVaccinePrice()*orderItem.getQuantity();
                dtm.addRow(row);
            }
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblUserAccount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrderHistory = new javax.swing.JTable();
        btnViewOrder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrderItem = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Welcome :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 87, -1, -1));

        lblUserAccount.setText("jLabel2");
        add(lblUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 87, -1, -1));

        tableOrderHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time Stamp", "Order ID", "Order status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableOrderHistory);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 119, 610, 90));

        btnViewOrder.setBackground(new java.awt.Color(102, 102, 255));
        btnViewOrder.setText("View Order");
        btnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderActionPerformed(evt);
            }
        });
        add(btnViewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 227, -1, -1));

        tableOrderItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Name", "Price", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableOrderItem);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 277, 610, 108));

        btnBack.setBackground(new java.awt.Color(102, 102, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 407, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
        // TODO add your handling code here:

        populateOrderItemTable();

    }//GEN-LAST:event_btnViewOrderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUserAccount;
    private javax.swing.JTable tableOrderHistory;
    private javax.swing.JTable tableOrderItem;
    // End of variables declaration//GEN-END:variables
}
