/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.cdcenterprise;

import business.Business;
import business.enterprise.CDCEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Harshil
 */
public class CDCEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CDCEnterpriseJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Network network;
    private Enterprise enterprise;
    private Organization organization;
    private Business business;
    
    
    public CDCEnterpriseJPanel(JPanel userProcessContainer, UserAccount userAccount,Network network,Enterprise enterprise,Organization organization,Business business) {
        initComponents();        
        this.organization = organization;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.enterprise = enterprise;
        this.network = network;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageVaccineCatalog = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CDC Enterprise WorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 11, -1, -1));

        btnManageVaccineCatalog.setBackground(new java.awt.Color(102, 102, 255));
        btnManageVaccineCatalog.setText("Manage Vaccine Catalog");
        btnManageVaccineCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVaccineCatalogActionPerformed(evt);
            }
        });
        add(btnManageVaccineCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 300, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Manage Work Requests");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 367, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/cdcenterprise/every-vaccination-is-a-little-victory.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageVaccineCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVaccineCatalogActionPerformed
        // TODO add your handling code here:
        
        ManageVaccineCatalogJPanel mvcjp = new ManageVaccineCatalogJPanel(userProcessContainer,userAccount,network,(CDCEnterprise)enterprise,business);
        userProcessContainer.add("ManageVaccineCatalogJPanel",mvcjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageVaccineCatalogActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        CDCWorkRequestsJPanel cwjp = new CDCWorkRequestsJPanel(userProcessContainer,userAccount,network,enterprise,organization,business);
        userProcessContainer.add("CDCWorkRequestsJPanel",cwjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageVaccineCatalog;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
