/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.cdcenterprise;

import business.Business;
import business.enterprise.CDCEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.useraccount.UserAccount;
import business.vaccine.Vaccine;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harshil
 */
public class ManageVaccineCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageVaccineCatalogJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Network network;
    private Business business;
    private CDCEnterprise cdcEnterprise;
    
    
    public ManageVaccineCatalogJPanel(JPanel userProcessContainer,UserAccount userAccount,Network network,CDCEnterprise cdcEnterprise,Business business) {
        initComponents();
        
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.business = business;
        this.cdcEnterprise = cdcEnterprise;
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vaccineCatalog = new javax.swing.JTable();
        btnCreateNewVaccine = new javax.swing.JButton();
        btnDeleteVaccine = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshButton.setBackground(new java.awt.Color(102, 102, 255));
        refreshButton.setText("Refresh");
        refreshButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        refreshButton.setMargin(new java.awt.Insets(2, 1, 2, 1));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 78, 80, -1));

        vaccineCatalog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vaccineCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Name", "Vaccine ID", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vaccineCatalog);
        if (vaccineCatalog.getColumnModel().getColumnCount() > 0) {
            vaccineCatalog.getColumnModel().getColumn(0).setResizable(false);
            vaccineCatalog.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 119, 500, 137));

        btnCreateNewVaccine.setBackground(new java.awt.Color(102, 102, 255));
        btnCreateNewVaccine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCreateNewVaccine.setText("Create New Vaccine >>");
        btnCreateNewVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewVaccineActionPerformed(evt);
            }
        });
        add(btnCreateNewVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 289, -1, -1));

        btnDeleteVaccine.setBackground(new java.awt.Color(102, 102, 255));
        btnDeleteVaccine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeleteVaccine.setText("Delete Vaccine(s)");
        btnDeleteVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVaccineActionPerformed(evt);
            }
        });
        add(btnDeleteVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 289, 190, -1));

        btnBack.setBackground(new java.awt.Color(102, 102, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTable()
    {
        int rowCount = vaccineCatalog.getRowCount();
        DefaultTableModel model = (DefaultTableModel)vaccineCatalog.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Vaccine vacc : cdcEnterprise.getApprovedVaccineCatalog().getVaccineList())
        {
            Object row[] = new Object[3];
            row[0] = vacc;
            row[1] = vacc.getVaccineID();
            row[2] = vacc.getVaccinePrice();
            model.addRow(row);
        }
    }
    
    
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void btnCreateNewVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewVaccineActionPerformed
        
        CreateNewVaccineJPanel cnvjp = new CreateNewVaccineJPanel(userProcessContainer,userAccount,cdcEnterprise,business);
        userProcessContainer.add("VaccineWorkAreaJPanel",cnvjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateNewVaccineActionPerformed

    private void btnDeleteVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVaccineActionPerformed
        // TODO add your handling code here:
        int row = vaccineCatalog.getSelectedRow();
        if(row >=0) 
        {
            Vaccine v = (Vaccine)vaccineCatalog.getValueAt(row, 0);
            
            int selectedOption = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete","Warning", JOptionPane.YES_NO_OPTION);
            if(selectedOption == JOptionPane.YES_NO_OPTION)
            {
                cdcEnterprise.getApprovedVaccineCatalog().removeVaccine(v);
                //refresh table
                refreshTable();
                
            }
            return;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a ROW", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
     
    }//GEN-LAST:event_btnDeleteVaccineActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateNewVaccine;
    private javax.swing.JButton btnDeleteVaccine;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable vaccineCatalog;
    // End of variables declaration//GEN-END:variables
}
